Repository Team-return/JOBIS-DSM-ANDROID, pull requests merged in 2023-09, with the labels that each got.

#96 🔗 :: (#94) system UI 개선
  presentation/src/main/java/team/retum/jobis_android/feature/main/MainScreen.kt
  presentation/src/main/java/team/retum/jobis_android/root/MainActivity.kt
  presentation/src/main/java/team/retum/jobis_android/root/navigation/JobisNavigation.kt
  presentation/src/main/java/team/retum/jobis_android/root/navigation/NavigationRoute.kt
  presentation/src/main/java/team/retum/jobis_android/util/compose/navigation/BottomBar.kt
  presentation/src/main/res/values/themes.xml
Labels: 리팩토링

#98 🔗 :: (#97) [BAC-533] 토큰 리프레시 구현
  data/src/main/java/team/retum/data/interceptor/AuthorizationInterceptor.kt
  data/src/main/java/team/retum/data/remote/api/UserApi.kt
  data/src/main/java/team/retum/data/remote/datasource/implementation/UserDataSourceImpl.kt
  data/src/main/java/team/retum/data/remote/response/user/SignInResponse.kt
  data/src/main/java/team/retum/data/remote/url/JobisUrl.kt
  data/src/main/java/team/retum/data/repository/UserRepositoryImpl.kt
  data/src/main/java/team/retum/data/storage/UserDataStorage.kt
  data/src/main/java/team/retum/data/storage/UserDataStorageImpl.kt
  di/src/main/java/team/retum/di/NetworkModule.kt
Labels: 기능 추가

#100 🔗 :: (#99) [BAC-545] 이미지 로직 수정
  data/src/main/java/team/retum/data/remote/url/JobisUrl.kt
  presentation/src/main/java/team/retum/jobis_android/feature/company/CompaniesScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/recruitment/RecruitmentsScreen.kt
  presentation/src/main/java/team/retum/jobis_android/viewmodel/company/CompanyViewModel.kt
  presentation/src/main/java/team/retum/jobis_android/viewmodel/mypage/MyPageViewModel.kt
  presentation/src/main/java/team/retum/jobis_android/viewmodel/recruitment/RecruitmentViewModel.kt
Labels: 리팩토링

#104 🔗 :: (#102) [BAC-534] collectAsStateWithLifecycle
  buildSrc/src/main/kotlin/Dependency.kt
  buildSrc/src/main/kotlin/Version.kt
  presentation/build.gradle.kts
  presentation/src/main/java/team/retum/jobis_android/feature/application/RecruitmentApplicationDialog.kt
  presentation/src/main/java/team/retum/jobis_android/feature/auth/changepassword/ComparePasswordScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/auth/resetpassword/ResetPasswordScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/auth/resetpassword/ResetPasswordVerifyEmailScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/auth/signin/SignInScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/auth/signup/SignUpScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/auth/signup/setpassword/SetPasswordScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/auth/signup/studentinfo/StudentInfoScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/auth/signup/verifyemail/VerifyEmailScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/bugreport/ReportBugScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/company/CompaniesScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/company/CompanyDetailsScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/home/BookmarkRecruitmentsScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/home/HomeScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/home/MyPageScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/recruitment/RecruitmentDetailsScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/recruitment/RecruitmentFilter.kt
  presentation/src/main/java/team/retum/jobis_android/feature/recruitment/RecruitmentsScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/review/PostReviewScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/review/ReviewDetailsScreen.kt
  presentation/src/main/java/team/retum/jobis_android/root/MainActivity.kt
Labels: 리팩토링

#105 🔗 :: (#101) 대규모 코드 리팩토링
  buildSrc/build/classes/kotlin/main/ProjectProperties.class
  buildSrc/src/main/kotlin/ProjectProperties.kt
  data/src/main/java/team/retum/data/interceptor/AuthorizationInterceptor.kt
  data/src/main/java/team/retum/data/remote/api/StudentApi.kt
  data/src/main/java/team/retum/data/remote/datasource/implementation/StudentsDataSourceImpl.kt
  data/src/main/java/team/retum/data/remote/response/company/FetchCompanyDetailResponse.kt
  data/src/main/java/team/retum/data/remote/response/recruitment/FetchRecruitmentDetailsResponse.kt
  di/src/main/java/team/retum/di/NetworkModule.kt
  domain/src/main/java/team/retum/domain/entity/company/CompanyDetailsEntity.kt
  domain/src/main/java/team/retum/domain/entity/recruitment/RecruitmentDetailsEntity.kt
  presentation/src/main/java/team/retum/jobis_android/contract/company/CompanyContract.kt
  presentation/src/main/java/team/retum/jobis_android/contract/mypage/MyPageContract.kt
  presentation/src/main/java/team/retum/jobis_android/feature/auth/signup/SignUpScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/bugreport/ReportBugScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/company/CompaniesScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/company/CompanyDetailsScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/home/HomeScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/home/MyPageScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/main/MainScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/recruitment/RecruitmentDetailsScreen.kt
  presentation/src/main/java/team/retum/jobis_android/root/MainActivity.kt
  presentation/src/main/java/team/retum/jobis_android/root/navigation/JobisNavigation.kt
  presentation/src/main/java/team/retum/jobis_android/root/navigation/NavigationRoute.kt
  presentation/src/main/java/team/retum/jobis_android/util/compose/navigation/BottomBar.kt
  presentation/src/main/java/team/retum/jobis_android/viewmodel/company/CompanyViewModel.kt
  presentation/src/main/java/team/retum/jobis_android/viewmodel/mypage/MyPageViewModel.kt
  presentation/src/main/res/values/strings.xml
Labels: 버그!!, 기능 추가, 리팩토링

#107 🔗 :: (#106) 앱 검토 사항 개선
  buildSrc/build/classes/kotlin/main/ProjectProperties.class
  buildSrc/src/main/kotlin/Dependency.kt
  buildSrc/src/main/kotlin/ProjectProperties.kt
  buildSrc/src/main/kotlin/Version.kt
  data/src/main/java/team/retum/data/remote/response/review/FetchReviewDetailsResponse.kt
  data/src/main/java/team/retum/data/util/HttpHandler.kt
  domain/src/main/java/team/retum/domain/entity/review/ReviewDetailsEntity.kt
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/team/retum/jobis_android/JobisApp.kt
  presentation/src/main/java/team/retum/jobis_android/JobisAppState.kt
  presentation/src/main/java/team/retum/jobis_android/MainActivity.kt
  presentation/src/main/java/team/retum/jobis_android/feature/application/RecruitmentApplicationDialog.kt
  presentation/src/main/java/team/retum/jobis_android/feature/auth/changepassword/ComparePasswordScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/auth/resetpassword/ResetPasswordScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/auth/resetpassword/ResetPasswordVerifyEmailScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/auth/signin/SignInScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/auth/signup/SignUpScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/bugreport/ReportBugScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/company/CompaniesScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/company/CompanyDetailsScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/main/BookmarkRecruitmentsScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/main/HomeScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/main/MenuScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/main/MyPageScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/recruitment/RecruitmentDetailsScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/recruitment/RecruitmentsScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/review/PostReviewScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/review/ReviewDetailsScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/root/RootScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/splash/SplashScreen.kt
  presentation/src/main/java/team/retum/jobis_android/navigation/AuthNavigation.kt
  presentation/src/main/java/team/retum/jobis_android/navigation/JobisNavigation.kt
  presentation/src/main/java/team/retum/jobis_android/navigation/MainNavigation.kt
  presentation/src/main/java/team/retum/jobis_android/navigation/NavigationProperties.kt
  presentation/src/main/java/team/retum/jobis_android/navigation/NavigationRoute.kt
  presentation/src/main/java/team/retum/jobis_android/navigation/UserNavigation.kt
  presentation/src/main/java/team/retum/jobis_android/root/MainActivity.kt
  presentation/src/main/java/team/retum/jobis_android/root/navigation/NavigationRoute.kt
  presentation/src/main/java/team/retum/jobis_android/util/compose/JobisBasicToast.kt
  presentation/src/main/java/team/retum/jobis_android/util/compose/component/JobisSnackBarHost.kt
  presentation/src/main/java/team/retum/jobis_android/util/compose/component/TopBar.kt
  presentation/src/main/java/team/retum/jobis_android/util/compose/navigation/BaseComposable.kt
  presentation/src/main/java/team/retum/jobis_android/util/compose/navigation/BottomBar.kt
  presentation/src/main/java/team/retum/jobis_android/util/compose/navigation/BottomNavigationItem.kt
  presentation/src/main/java/team/retum/jobis_android/viewmodel/bookmark/BookmarkViewModel.kt
  presentation/src/main/java/team/retum/jobis_android/viewmodel/main/MainViewModel.kt
  presentation/src/main/java/team/retum/jobis_android/viewmodel/review/ReviewViewModel.kt
  presentation/src/main/res/values-night/themes.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/themes.xml
Labels: 버그!!, 리팩토링

#111 🔗 :: (#110) 버그 제보 이미지 버그 수정
  presentation/src/main/java/team/retum/jobis_android/feature/bugreport/ReportBugScreen.kt
  presentation/src/main/java/team/retum/jobis_android/viewmodel/bugreport/BugViewModel.kt
Labels: 버그!!

#115 🔗 :: (#114) recruitments companies paging 로직 구현
  presentation/src/main/java/team/retum/jobis_android/contract/company/CompanyContract.kt
  presentation/src/main/java/team/retum/jobis_android/contract/recruitment/RecruitmentContract.kt
  presentation/src/main/java/team/retum/jobis_android/feature/company/CompaniesScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/recruitment/RecruitmentsScreen.kt
  presentation/src/main/java/team/retum/jobis_android/viewmodel/company/CompanyViewModel.kt
  presentation/src/main/java/team/retum/jobis_android/viewmodel/recruitment/RecruitmentViewModel.kt
Labels: 기능 추가

#118 🔗 :: (#116) [BAC-572] 텍스트 인풋 커서 밀림 버그 수정
  .idea/libraries/Gradle__org_orbit_mvi_orbit_core_jvm_4_5_0.xml
  .idea/libraries/Gradle__org_orbit_mvi_orbit_test_jvm_4_5_0.xml
  buildSrc/.gradle/7.3/checksums/checksums.lock
  buildSrc/.gradle/7.3/dependencies-accessors/dependencies-accessors.lock
  buildSrc/.gradle/7.3/dependencies-accessors/gc.properties
  buildSrc/.gradle/7.3/executionHistory/executionHistory.lock
  buildSrc/.gradle/7.3/fileChanges/last-build.bin
  buildSrc/.gradle/7.3/fileHashes/fileHashes.lock
  buildSrc/.gradle/7.3/gc.properties
  buildSrc/src/main/kotlin/Version.kt
  presentation/src/main/java/team/retum/jobis_android/feature/application/RecruitmentApplicationDialog.kt
  presentation/src/main/java/team/retum/jobis_android/feature/auth/changepassword/ComparePasswordScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/auth/resetpassword/ResetPasswordScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/auth/resetpassword/ResetPasswordVerifyEmailScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/auth/signin/SignInScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/auth/signup/SignUpScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/auth/signup/setpassword/SetPasswordScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/auth/signup/studentinfo/StudentInfoScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/auth/signup/verifyemail/VerifyEmailScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/bugreport/ReportBugScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/company/CompaniesScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/main/MyPageScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/recruitment/RecruitmentFilter.kt
  presentation/src/main/java/team/retum/jobis_android/feature/recruitment/RecruitmentsScreen.kt
Labels: 버그!!, 리팩토링, 프로젝트 세팅

#119 🔗 :: (#117) [BAC-574] infinite recomposition
  data/src/main/java/team/retum/data/remote/api/CompanyApi.kt
  data/src/main/java/team/retum/data/remote/api/RecruitmentApi.kt
  data/src/main/java/team/retum/data/remote/datasource/company/CompanyDataSource.kt
  data/src/main/java/team/retum/data/remote/datasource/company/CompanyDataSourceImpl.kt
  data/src/main/java/team/retum/data/remote/datasource/recruitment/RecruitmentDataSource.kt
  data/src/main/java/team/retum/data/remote/datasource/recruitment/RecruitmentDataSourceImpl.kt
  data/src/main/java/team/retum/data/remote/response/company/FetchCompanyCountResponse.kt
  data/src/main/java/team/retum/data/remote/response/recruitment/FetchRecruitmentCountResponse.kt
  data/src/main/java/team/retum/data/remote/url/JobisUrl.kt
  data/src/main/java/team/retum/data/repository/CompanyRepositoryImpl.kt
  data/src/main/java/team/retum/data/repository/RecruitmentRepositoryImpl.kt
  domain/src/main/java/team/retum/domain/entity/company/CompanyCountEntity.kt
  domain/src/main/java/team/retum/domain/entity/recruitment/RecruitmentCountEntity.kt
  domain/src/main/java/team/retum/domain/repository/CompanyRepository.kt
  domain/src/main/java/team/retum/domain/repository/RecruitmentRepository.kt
  domain/src/main/java/team/retum/domain/usecase/company/FetchCompanyCountUseCase.kt
  domain/src/main/java/team/retum/domain/usecase/recruitment/FetchRecruitmentCountUseCase.kt
  presentation/src/main/java/team/retum/jobis_android/contract/company/CompanyContract.kt
  presentation/src/main/java/team/retum/jobis_android/contract/recruitment/RecruitmentContract.kt
  presentation/src/main/java/team/retum/jobis_android/feature/company/CompaniesScreen.kt
  presentation/src/main/java/team/retum/jobis_android/feature/recruitment/RecruitmentsScreen.kt
  presentation/src/main/java/team/retum/jobis_android/viewmodel/company/CompanyViewModel.kt
  presentation/src/main/java/team/retum/jobis_android/viewmodel/recruitment/RecruitmentViewModel.kt
Labels: 버그!!
